
username = "Sharp"

load_models = false
load_sprites = true

resolution_w = 1024
resolution_h = 768

# possible values: ["OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"]
log_level = "TRACE"


grf_paths = [
  "/media/sharp/ext4_hdd/Games/TalonRO/rdata.grf",
  "/media/sharp/ext4_hdd/Games/TalonRO/sdata.grf",
  "/media/sharp/ext4_hdd/Games/TalonRO/tdata.grf",
]

server_addr = "127.0.0.1:6969"

# aka quick cast, Normal, OnKeyRelease, OnKeyPress
cast_mode = "Normal"

show_last_acknowledged_pos = true
# it takes x ticks for acked_pos to reach the predicted pos
lerping_ticks = 3
lerping_enabled = false

max_fps = 60