
# possible values: ["OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"]
log_level = "TRACE"

# if true, many resources won't be loaded (static models, gat data etc)
quick_startup = false

grf_paths = [
  "d:\\Games\\TalonRO\\rdata.grf",
  "d:\\Games\\TalonRO\\sdata.grf",
  "d:\\Games\\TalonRO\\tdata.grf"
]