
# possible values: ["OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"]
log_level = "TRACE"

# if true, many resources won't be loaded (static models, gat data etc)
quick_startup = false

grf_paths = [
  "/media/sharp/9C16370C1636E744/Games/TalonRO/rdata.grf",
  "/media/sharp/9C16370C1636E744/Games/TalonRO/sdata.grf",
  "/media/sharp/9C16370C1636E744/Games/TalonRO/tdata.grf",
]