load_models = true
load_sprites = true

map_name = "prontera"

resolution_w = 1024
resolution_h = 768

# right gate: 250.0, -200.0
start_pos_x = 238
start_pos_y = -65
# possible values: ["OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"]
log_level = "DEBUG"


grf_paths = [
  "/media/sharp/9C16370C1636E744/Games/TalonRO/rdata.grf",
  "/media/sharp/9C16370C1636E744/Games/TalonRO/sdata.grf",
  "/media/sharp/9C16370C1636E744/Games/TalonRO/tdata.grf",
]

server_port = 6969
server_addr = "127.0.0.1:6969"

# aka quick cast, Normal, OnKeyRelease, OnKeyPress
cast_mode = "Normal"

show_last_acknowledged_pos = true
# it takes x ticks for acked_pos to reach the predicted pos
lerping_ticks = 3
lerping_enabled = false

max_fps = 60